spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: elastic-query-web-client,config-client