spring:
  application:
    name: elastic-query-service
  profiles:
    active: elastic_query
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: elastic-query-service,config-client


